version: '3.7'
services:
  app:
    build: .
    environment:
      APP_DB_HOST: db
      APP_DB_USER: root
      APP_DB_PASS: password
      APP_DB_NAME: message
    expose:
      - 3000
    ports:
      - "3000:3000"
    volumes:
      - ./:/usr/src/myapp
    working_dir: "/usr/src/myapp"
    links:
      - db
    command: realize start --run
  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: message
      MYSQL_ROOT_PASSWORD: password
    expose:
      - 3306
    ports:
      - "3306:3306"
    volumes:
      - ./misc/ddl/message_tables.sql:/docker-entrypoint-initdb.d/1_message_table.sql
    command: |
      mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_bin --general_log=1 --general_log_file=/var/log/mysql/query.log

